(in-package #:cl-weave/tests)

(describe "cli metadata contracts"
  (it "keeps README adoption and CI contracts synchronized with metadata"
    (let* ((readme (read-text-file (merge-pathnames #P"README.md"
                                                    (uiop:getcwd))))
           (normalized-readme (normalize-shell-text readme))
           (metadata (cl-weave/cli::framework-metadata))
           (gates (getf metadata :quality-gates)))
      (expect readme :to-contain "## Adoption")
      (expect readme :to-contain "### AI Discovery")
      (expect readme :to-contain "## CI")
      (dolist (gate gates)
        (expect normalized-readme
                :to-contain
                (normalize-shell-text
                 (workflow-command-string (getf gate :command))))
        (dolist (artifact (getf gate :artifacts))
          (expect readme :to-contain artifact)))))

  (it "keeps mutation artifact schema aligned with mutation reporters"
    (let* ((schema (find "mutations"
                         (cl-weave:reporter-artifact-schemas)
                         :key (lambda (entry) (getf entry :kind))
                         :test #'string=))
           (field-names (mapcar (lambda (entry) (getf entry :name))
                                (getf schema :fields)))
           (results (run-mutations '(+ 1 1)
                                   (lambda (form mutation)
                                     (declare (ignore mutation))
                                     (= (eval form) 2))))
           (json-output (with-output-to-string (stream)
                          (report-mutations-json results stream))))
      (expect schema :not :to-be nil)
      (expect field-names
              :to-equal '("schemaVersion" "kind" "total" "killed"
                          "survived" "errored" "score" "results"))
      (dolist (field field-names)
        (expect json-output :to-contain (format nil "\"~A\"" field)))
      (expect json-output :not :to-contain "\"operators\"")
      (expect json-output :not :to-contain "\"summary\"")))

  (it "derives artifact schema metadata from reporter contracts"
    (expect (cl-weave:reporter-artifact-schemas)
            :to-be cl-weave::*reporter-artifact-schemas*)
    (expect (getf (cl-weave/cli::framework-metadata) :artifact-schemas)
            :to-be (cl-weave:reporter-artifact-schemas)))

  (it "exposes framework metadata through the public Lisp API"
    (let ((public-metadata (cl-weave:framework-metadata))
          (cli-metadata (cl-weave/cli::framework-metadata)))
      (expect public-metadata :to-equal cli-metadata)
      (expect (getf public-metadata :artifact-schemas)
              :to-equal (cl-weave:reporter-artifact-schemas))
      (expect (getf public-metadata :citation)
              :to-equal (getf cli-metadata :citation))))

  (it "keeps artifact schemas aligned with command reporter contracts"
    (labels ((reporter-choices-for (command metadata)
               (cond
                 ((string= command "run")
                 (getf metadata :reporters))
                 ((string= command "watch")
                  (getf metadata :reporters))
                 ((string= command "list")
                  (getf metadata :list-reporters))
                 ((string= command "doctor")
                  '("json" "sexp"))
                 (t '())))
             (expect-schema-reporters-valid-for-command (schema metadata)
               (let ((commands (getf schema :commands)))
                 (when commands
                   (expect commands :to-satisfy #'listp)
                   (dolist (command commands)
                     (expect (member command (getf metadata :commands) :test #'string=)
                             :not :to-be nil)
                     (let ((choices (reporter-choices-for command metadata)))
                       (expect choices :to-satisfy #'consp)
                       (dolist (reporter (getf schema :reporters))
                         (expect (member reporter choices :test #'string=)
                                 :not :to-be nil))))))))
      (let ((metadata (cl-weave/cli::framework-metadata)))
        (dolist (schema (getf metadata :artifact-schemas))
          (expect-schema-reporters-valid-for-command schema metadata)
          (if (getf schema :streaming)
              (expect (getf schema :reporters) :to-equal '("jsonl"))
              (expect (getf schema :reporters) :not :to-contain "jsonl"))))))

  (it "keeps reporter metadata synchronized with implemented reporters"
    (flet ((reporter-name (reporter)
             (string-downcase (symbol-name reporter))))
      (let ((metadata (cl-weave/cli::framework-metadata)))
        (expect (getf metadata :reporters)
                :to-equal (mapcar #'reporter-name cl-weave::*run-reporters*))
        (expect (getf metadata :list-reporters)
                :to-equal (mapcar #'reporter-name cl-weave::*list-reporters*)))))

  (it "keeps package export metadata synchronized with actual packages"
    (flet ((actual-exports (package-name)
             (let ((exports '()))
               (do-external-symbols (symbol (find-package (string-upcase package-name)))
                 (push (symbol-name symbol) exports))
               (sort exports #'string<)))
           (metadata-exports (package-name metadata)
             (getf (find package-name
                         (getf metadata :package-exports)
                         :key (lambda (entry) (getf entry :name))
                         :test #'string=)
                   :exports)))
      (let ((metadata (cl-weave/cli::framework-metadata)))
        (let ((declared-core (metadata-exports "cl-weave" metadata))
              (actual-core (actual-exports "cl-weave"))
              (declared-cli (metadata-exports "cl-weave/cli" metadata))
              (actual-cli (actual-exports "cl-weave/cli")))
          (expect declared-core :to-equal actual-core)
          (expect declared-cli :to-equal actual-cli)))))

  (it "keeps framework metadata identifiers unique"
    (labels ((duplicate-strings (values)
               (let ((seen (make-hash-table :test #'equal))
                     (duplicates '()))
                 (dolist (value values)
                   (if (gethash value seen)
                       (pushnew value duplicates :test #'string=)
                       (setf (gethash value seen) t)))
                 (sort duplicates #'string<)))
             (expect-unique-strings (values)
               (expect (duplicate-strings values) :to-equal '()))
             (metadata-names (entries)
               (mapcar (lambda (entry)
                         (string-downcase (symbol-name (getf entry :name))))
                       entries)))
      (let ((metadata (cl-weave/cli::framework-metadata)))
        (dolist (key '(:commands :reporters :list-reporters
                       :capabilities :environment))
          (expect-unique-strings (getf metadata key)))
        (expect-unique-strings
         (mapcar (lambda (entry) (getf entry :name))
                 (getf metadata :capability-matrix)))
        (dolist (entry (getf metadata :capability-matrix))
          (expect (member (getf entry :name)
                          (getf metadata :capabilities)
                          :test #'string=)
                  :not :to-be nil)
          (expect (getf entry :status) :to-equal "implemented")
          (expect (getf entry :summary) :to-satisfy #'stringp)
          (expect (getf entry :public-apis) :to-satisfy #'consp)
          (expect-unique-strings (getf entry :public-apis))
          (dolist (api-name (getf entry :public-apis))
            (multiple-value-bind (symbol status)
                (find-symbol (string-upcase api-name) '#:cl-weave)
              (expect symbol :not :to-be nil)
              (expect status :to-be :external)))
          (expect (getf entry :quality-gates) :to-satisfy #'consp)
          (expect-unique-strings (getf entry :quality-gates))
          (dolist (gate-name (getf entry :quality-gates))
            (expect (find gate-name (getf metadata :quality-gates)
                          :key (lambda (gate) (getf gate :name))
                          :test #'string=)
                    :not :to-be nil))
          (expect (getf entry :documentation) :to-satisfy #'consp)
          (expect-unique-strings (getf entry :documentation))
          (dolist (document (getf entry :documentation))
            (expect (probe-file (merge-pathnames document (uiop:getcwd)))
                    :not :to-be nil)))
        (dolist (capability (getf metadata :capabilities))
          (expect (find capability
                        (getf metadata :capability-matrix)
                        :key (lambda (entry) (getf entry :name))
                        :test #'string=)
                  :not :to-be nil))
        (expect-unique-strings (getf metadata :policy-documents))
        (dolist (document (getf metadata :policy-documents))
          (expect (probe-file (merge-pathnames document (uiop:getcwd)))
                  :not :to-be nil))
        (expect-unique-strings
         (mapcar (lambda (entry)
                   (getf entry :name))
                 (getf metadata :reference-documents)))
        (expect-unique-strings
         (mapcar (lambda (entry) (getf entry :path))
                 (getf metadata :reference-documents)))
        (dolist (entry (getf metadata :reference-documents))
          (expect (getf entry :description) :to-satisfy #'stringp)
          (expect (probe-file (merge-pathnames (getf entry :path) (uiop:getcwd)))
                  :not :to-be nil))
        (expect-unique-strings
         (mapcar (lambda (entry) (getf entry :name))
                 (getf metadata :support-channels)))
        (dolist (entry (getf metadata :support-channels))
          (expect (getf entry :scope) :to-satisfy #'stringp)
          (when (string= (getf entry :kind) "document")
            (expect (probe-file (merge-pathnames (getf entry :target) (uiop:getcwd)))
                    :not :to-be nil)))
        (expect-unique-strings
         (mapcar (lambda (entry) (getf entry :name))
                 (getf metadata :community-health)))
        (dolist (entry (getf metadata :community-health))
          (expect (getf entry :kind) :to-satisfy #'stringp)
          (expect (getf entry :path) :to-satisfy #'stringp)
          (expect (probe-file (merge-pathnames (getf entry :path) (uiop:getcwd)))
                  :not :to-be nil)
          (expect (getf entry :references) :to-satisfy #'listp)
          (expect-unique-strings (getf entry :references))
          (dolist (reference (getf entry :references))
            (expect (probe-file (merge-pathnames reference (uiop:getcwd)))
                    :not :to-be nil))
          (expect (getf entry :required-sections) :to-satisfy #'listp)
          (expect-unique-strings (getf entry :required-sections))
          (expect (getf entry :contact-links) :to-satisfy #'listp)
          (expect-unique-strings
           (mapcar (lambda (link) (getf link :name))
                   (getf entry :contact-links)))
          (dolist (link (getf entry :contact-links))
            (expect (getf link :target) :to-satisfy #'stringp)
            (expect (getf link :purpose) :to-satisfy
                    (lambda (value) (or (null value) (stringp value))))))
        (expect-unique-strings
         (mapcar (lambda (entry) (getf entry :name))
                 (getf metadata :security-contacts)))
        (dolist (entry (getf metadata :security-contacts))
          (expect (getf entry :scope) :to-satisfy #'stringp)
          (when (string= (getf entry :kind) "document")
            (expect (probe-file (merge-pathnames (getf entry :target) (uiop:getcwd)))
                    :not :to-be nil)))
        (let ((lifecycle (getf metadata :lifecycle)))
          (dolist (key '(:support-document :versioning-document :security-document))
            (expect (probe-file (merge-pathnames (getf lifecycle key) (uiop:getcwd)))
                    :not :to-be nil)))
        (let ((runtime-support (getf metadata :runtime-support)))
          (expect (probe-file (merge-pathnames (getf runtime-support :policy-document)
                                               (uiop:getcwd)))
                  :not :to-be nil)
          (expect-unique-strings
           (mapcar (lambda (entry) (getf entry :implementation))
                   (getf runtime-support :supported-targets)))
          (expect-unique-strings
           (mapcar (lambda (entry) (getf entry :implementation))
                   (getf runtime-support :best-effort-targets)))
          (dolist (entry (append (getf runtime-support :supported-targets)
                                 (getf runtime-support :best-effort-targets)))
            (expect (getf entry :status) :to-satisfy #'stringp)
            (expect (getf entry :platforms) :to-satisfy #'listp)
            (expect-unique-strings (getf entry :platforms)))
          (expect-unique-strings
           (getf runtime-support :implementation-specific-features)))
        (let ((release-process (getf metadata :release-process)))
          (expect (probe-file (merge-pathnames (getf release-process :policy-document)
                                               (uiop:getcwd)))
                  :not :to-be nil)
          (expect-unique-strings (getf release-process :checklist))
          (expect-unique-strings
           (getf release-process :contract-sync-requirements)))
        (let ((ci (getf metadata :continuous-integration)))
          (expect (probe-file (merge-pathnames (getf ci :workflow-path)
                                               (uiop:getcwd)))
                  :not :to-be nil)
          (expect-unique-strings (getf ci :triggers))
          (expect-unique-strings (getf ci :systems))
          (expect-unique-strings (getf ci :cache-modes)))
        (expect-unique-strings
         (mapcar (lambda (entry) (getf entry :name))
                 (getf metadata :options)))
        (dolist (entry (getf metadata :options))
          (expect (member :aliases entry) :to-be nil)
          (expect (getf entry :value-kind) :not :to-be nil)
          (expect (member :choices entry) :not :to-be nil)
          (expect (getf entry :choices) :to-satisfy #'listp)
          (expect-unique-strings (getf entry :choices))
          (dolist (command-entry (getf entry :command-choices))
            (destructuring-bind (command choices) command-entry
              (expect (member command (getf entry :commands) :test #'string=)
                      :not :to-be nil)
              (expect-unique-strings choices)
              (dolist (choice choices)
                (expect (member choice (getf entry :choices) :test #'string=)
                        :not :to-be nil))))
          (dolist (command (getf entry :commands))
            (expect (member command (getf metadata :commands) :test #'string=)
                    :not :to-be nil))
          (dolist (variable (getf entry :environment))
            (expect (member variable (getf metadata :environment) :test #'string=)
                    :not :to-be nil)))
        (expect-unique-strings (mapcar (lambda (entry) (getf entry :name))
                                       (getf metadata :package-exports)))
        (dolist (entry (getf metadata :package-exports))
          (expect-unique-strings (getf entry :exports)))
        (expect-unique-strings (metadata-names (getf metadata :matchers)))
        (dolist (matcher '("to-allocate-under" "to-have-slot"
                           "to-have-method-specialized-on"))
          (expect (member matcher (metadata-names (getf metadata :matchers))
                          :test #'string=)
                  :not :to-be nil))
        (expect (member "mop-architecture-assertions"
                        (getf metadata :capabilities)
                        :test #'string=)
                :not :to-be nil)
        (expect (member "artifact-schemas"
                        (getf metadata :capabilities)
                        :test #'string=)
                :not :to-be nil)
        (expect-unique-strings (metadata-names (getf metadata :mutation-operators)))
        (expect-unique-strings
         (mapcar (lambda (entry) (getf entry :kind))
                 (getf metadata :artifact-schemas)))
        (expect-unique-strings
         (mapcar (lambda (entry) (getf entry :name))
                 (getf metadata :quality-gates)))
        (dolist (entry (getf metadata :quality-gates))
          (expect (getf entry :name) :to-satisfy #'stringp)
          (expect (getf entry :kind) :to-satisfy #'stringp)
          (expect (getf entry :command) :to-satisfy #'consp)
          (expect (getf entry :timeout-seconds) :to-satisfy #'plusp)
          (expect (getf entry :artifacts) :to-satisfy #'listp)
          (expect (getf entry :description) :to-satisfy
                  (lambda (value) (or (null value) (stringp value))))
          (dolist (argument (getf entry :command))
            (expect argument :to-satisfy #'stringp))
          (dolist (artifact (getf entry :artifacts))
            (expect artifact :to-satisfy #'stringp)))
        (dolist (entry (getf metadata :artifact-schemas))
          (expect (getf entry :schema-version) :to-satisfy #'plusp)
          (expect (getf entry :streaming) :to-satisfy
                  (lambda (value) (member value '(nil t))))
          (expect (getf entry :commands) :to-satisfy #'listp)
          (expect-unique-strings (getf entry :commands))
          (dolist (command (getf entry :commands))
            (expect (member command
                            (getf metadata :commands)
                            :test #'string=)
                    :not :to-be nil))
          (dolist (reporter (getf entry :reporters))
            (expect (member reporter (getf metadata :reporters) :test #'string=)
                    :not :to-be nil))
          (expect (getf entry :fields) :to-satisfy #'consp)
          (expect-unique-strings
           (mapcar (lambda (field) (getf field :name))
                   (getf entry :fields)))
          (dolist (field (getf entry :fields))
            (expect (getf field :name) :to-satisfy #'stringp)
            (expect (getf field :kind) :to-satisfy #'stringp)
            (expect (getf field :required) :to-satisfy
                    (lambda (value) (member value '(nil t))))
            (expect (getf field :description) :to-satisfy
                    (lambda (value) (or (null value) (stringp value))))))
        (dolist (reporter (getf metadata :list-reporters))
          (expect (member reporter (getf metadata :reporters) :test #'string=)
                  :not :to-be nil)))))

  (it "advertises framework metadata in machine-readable capability APIs"
    (let ((capability-matrix
            (getf (cl-weave/cli::framework-metadata) :capability-matrix)))
      (dolist (capability-name '("structured-reporting"
                                 "artifact-schemas"
                                 "ai-discovery-metadata"
                                 "public-package-exports"))
        (let* ((entry (find capability-name
                            capability-matrix
                            :key (lambda (item) (getf item :name))
                            :test #'string=))
               (public-apis (getf entry :public-apis)))
          (expect entry :not :to-be nil)
          (expect public-apis :to-contain "framework-metadata")))))

  (it "keeps environment specs aligned with environment-backed metadata"
    (dolist (entry cl-weave/cli::*metadata-cli-options*)
      (let ((name (getf entry :name))
            (environment (getf entry :environment)))
        (if environment
            (expect (cl-weave/cli::cli-environment-spec name)
                    :not :to-be nil)
            (expect (cl-weave/cli::cli-environment-spec name)
                    :to-be nil)))))
)
