(defpackage #:cl-weave/tests
  (:use #:cl)
  (:shadowing-import-from #:cl-weave
   #:describe)
  (:import-from #:cl-weave
   #:*test-context*
   #:around-each
   #:after-all
   #:after-each
   #:assertion-failure
   #:before-all
   #:before-each
   #:clear-all-mocks
   #:clear-mock
   #:clear-tests
   #:collect-mutations
   #:continue-test
   #:defmatcher
   #:defmutation-operator
   #:describe.concurrent
   #:describe.concurrent.each
   #:describe.each
   #:describe.only
   #:describe.only.each
   #:describe.run-if
   #:describe.sequential
   #:describe.sequential.each
   #:describe.skip
   #:describe.skip.each
   #:describe.skip-if
   #:describe.todo
   #:describe.todo.each
   #:describe-concurrent
   #:describe-concurrent-each
   #:describe-each
   #:describe-only
   #:describe-only-each
   #:describe-sequential
   #:describe-sequential-each
   #:describe-run-if
   #:describe-skip
   #:describe-skip-each
   #:describe-skip-if
   #:describe-todo
   #:describe-todo-each
   #:extend-expect
   #:expect
   #:expect.assertions
   #:expect-assertions
   #:expect.extend
   #:expect-extend
   #:expect.hasassertions
   #:expect-has-assertions
   #:expect.not
   #:expect-not
   #:expect.rejects
   #:expect-rejects
   #:expect.resolves
   #:expect-resolves
   #:gen-boolean
   #:gen-form
   #:gen-integer
   #:gen-keyword
   #:gen-list
   #:gen-map
   #:gen-member
   #:gen-one-of
   #:gen-recursive
   #:gen-sexp
   #:gen-such-that
   #:gen-symbol
   #:gen-tuple
   #:it
   #:it.concurrent
   #:it.concurrent.each
   #:it.each
   #:it-concurrent
   #:it-concurrent-each
   #:it-each
   #:it.fails
   #:it.fails.each
   #:it-fails
   #:it-fails-each
   #:it.isolated
   #:it-isolated
   #:it.property
   #:it-property
   #:it.only
   #:it.only.each
   #:it-only
   #:it-only-each
   #:it.run-if
   #:it-run-if
   #:it.sequential
   #:it.sequential.each
   #:it-sequential
   #:it-sequential-each
   #:it.skip
   #:it.skip.each
   #:it-skip
   #:it-skip-each
   #:it.skip-if
   #:it-skip-if
   #:it.todo
   #:it.todo.each
   #:it-todo
   #:it-todo-each
   #:isolated-result-exit-code
   #:isolated-result-status
   #:isolated-result-stderr
   #:isolated-result-timed-out-p
   #:list-mutation-operators
   #:logic-query
   #:logic-variable-p
   #:logic-where
   #:make-mock-function
   #:mock-function-p
   #:mock-implementation
   #:mock-return-value
   #:mock-return-values
   #:reset-all-mocks
   #:reset-mock
   #:restore-all-mocks
   #:mock-restore
   #:spy-on
   #:with-continuation-result
   #:with-continuation-values
   #:vi.clearallmocks
   #:vi.fn
   #:vi.ismockfunction
   #:vi.mocked
   #:vi.mockclear
   #:vi.mockimplementation
   #:vi.mockreset
   #:vi.mockrestore
   #:vi.mockreturnvalue
   #:vi.mockreturnvalues
   #:vi.resetallmocks
   #:vi.restoreallmocks
   #:vi.spyon
   #:mock-calls
   #:mock-results
   #:mutation-form
   #:mutation-id
   #:mutation-operator
   #:mutation-operator-metadata
   #:mutation-original
   #:mutation-path
   #:mutation-replacement
   #:mutation-result-status
   #:mutation-summary
   #:report-mutations-json
   #:report-mutations-sexp
   #:query-test-plan
   #:run-isolated
   #:run-mutations
   #:retry-test
   #:skip-test
   #:test
   #:test.concurrent
   #:test.concurrent.each
   #:test.each
   #:test-concurrent
   #:test-concurrent-each
   #:test-each
   #:test.fails
   #:test.fails.each
   #:test-fails
   #:test-fails-each
   #:test.isolated
   #:test-isolated
   #:test.only
   #:test.only.each
   #:test-only
   #:test-only-each
   #:test.property
   #:test-property
   #:test-plan-facts
   #:test-plan-where
   #:test.run-if
   #:test-run-if
   #:test.sequential
   #:test.sequential.each
   #:test-sequential
   #:test-sequential-each
   #:test.skip
   #:test.skip.each
   #:test-skip
   #:test-skip-each
   #:test.skip-if
   #:test-skip-if
   #:test.todo
   #:test.todo.each
   #:test-todo
   #:test-todo-each
   #:with-mocked-functions))
