(defpackage #:cl-weave/tests
  (:use #:cl)
  (:shadowing-import-from #:cl-weave
   #:describe)
  (:import-from #:cl-weave
   #:*test-context*
   #:after-all
   #:after-each
   #:assertion-failure
   #:before-all
   #:before-each
   #:clear-mock
   #:clear-tests
   #:collect-mutations
   #:defmatcher
   #:defmutation-operator
   #:describe-each
   #:describe-run-if
   #:describe-skip
   #:describe-skip-if
   #:describe-todo
   #:expect
   #:expect-not
   #:gen-boolean
   #:gen-form
   #:gen-integer
   #:gen-keyword
   #:gen-list
   #:gen-map
   #:gen-member
   #:gen-one-of
   #:gen-recursive
   #:gen-sexp
   #:gen-such-that
   #:gen-symbol
   #:gen-tuple
   #:it
   #:it-concurrent
   #:it-each
   #:it-fails
   #:it-isolated
   #:it-property
   #:it-only
   #:it-run-if
   #:it-skip
   #:it-skip-if
   #:it-todo
   #:isolated-result-exit-code
   #:isolated-result-status
   #:isolated-result-stderr
   #:isolated-result-timed-out-p
   #:make-mock-function
   #:mock-calls
   #:mutation-form
   #:mutation-id
   #:mutation-operator
   #:mutation-original
   #:mutation-path
   #:mutation-replacement
   #:mutation-result-status
   #:mutation-summary
   #:report-mutations-json
   #:report-mutations-sexp
   #:run-isolated
   #:run-mutations
   #:test-concurrent
   #:test-each
   #:test-fails
   #:test-run-if
   #:test-skip-if
   #:with-mocked-functions))
