(in-package #:cl-weave/cli)

(define-cli-options
  (:fields
   (command :run :type keyword)
   (systems '() :type list)
   (load-files '() :type list)
   (reporter :spec :type keyword)
   name-filter output-file list watch watch-once
   (watch-interval 0.5)
   bail
   (retry 0)
   test-timeout-ms max-workers shard
   (order nil :type (or null keyword))
   seed coverage coverage-output
   (pass-with-no-tests t)
   snapshot-directory snapshot-file update-snapshots version help)
  (:options
   (:flag "--help" :kind :flag :field :help)
   (:flag "--version" :kind :flag :field :version)
   (:flag "--list" :kind :flag :field :list :command :list)
   (:flag "--watch" :kind :flag :field :watch :command :watch)
   (:flag "--once" :kind :flag :field :watch-once)
   (:flag "--coverage" :kind :flag :field :coverage)
   (:flag "--pass-with-no-tests" :kind :flag :field :pass-with-no-tests)
   (:flag "--fail-with-no-tests" :kind :flag :field :pass-with-no-tests :value nil)
   (:flag "--update-snapshots" :kind :flag :field :update-snapshots)
   (:flag "--system" :kind :collection :field :systems)
   (:flag "--load" :kind :collection :field :load-files)
   (:flag "--reporter" :kind :value :field :reporter :parser parse-reporter-option)
   (:flag "--filter" :kind :value :field :name-filter)
   (:flag "--output" :kind :value :field :output-file)
   (:flag "--watch-interval" :kind :value :field :watch-interval :parser parse-positive-number)
   (:flag "--retry" :kind :value :field :retry :parser parse-non-negative-integer)
   (:flag "--test-timeout-ms" :kind :value :field :test-timeout-ms :parser parse-positive-integer)
   (:flag "--max-workers" :kind :value :field :max-workers :parser parse-positive-integer)
   (:flag "--shard" :kind :value :field :shard :parser parse-shard-option)
   (:flag "--sequence" :kind :value :field :order :parser parse-sequence-order-option)
   (:flag "--seed" :kind :value :field :seed :parser parse-positive-integer)
   (:flag "--coverage-output" :kind :value :field :coverage-output)
   (:flag "--snapshot-dir" :kind :value :field :snapshot-directory :parser parse-pathname-option)
   (:flag "--snapshot-file" :kind :value :field :snapshot-file)
   (:flag "--bail" :kind :optional-value :field :bail :parser parse-bail-option :default "true"))
  (:environment
   (:flag "--system" :kind :value :field :systems :parser parse-system-list-option)
   (:flag "--reporter" :kind :value :field :reporter :parser parse-reporter-option)
   (:flag "--filter" :kind :value :field :name-filter)
   (:flag "--output" :kind :value :field :output-file)
   (:flag "--watch-interval" :kind :value :field :watch-interval :parser parse-positive-number)
   (:flag "--bail" :kind :value :field :bail :parser parse-bail-option)
   (:flag "--retry" :kind :value :field :retry :parser parse-non-negative-integer)
   (:flag "--test-timeout-ms" :kind :value :field :test-timeout-ms :parser parse-positive-integer)
   (:flag "--max-workers" :kind :value :field :max-workers :parser parse-positive-integer)
   (:flag "--shard" :kind :value :field :shard :parser parse-shard-option)
   (:flag "--sequence" :kind :value :field :order :parser parse-sequence-order-option)
   (:flag "--seed" :kind :value :field :seed :parser parse-positive-integer)
   (:flag "--coverage-output" :kind :value :field :coverage-output)
   (:flag "--pass-with-no-tests" :kind :value :field :pass-with-no-tests :parser parse-boolean)
   (:flag "--snapshot-dir" :kind :value :field :snapshot-directory :parser parse-pathname-option)
   (:flag "--snapshot-file" :kind :value :field :snapshot-file)
   (:flag "--list" :kind :truthy :field :list :command :list)
   (:flag "--watch" :kind :truthy :field :watch :command :watch)
   (:flag "--once" :kind :truthy :field :watch-once)
   (:flag "--coverage" :kind :truthy :field :coverage)
   (:flag "--update-snapshots" :kind :truthy :field :update-snapshots)))
