(in-package #:cl-weave/cli)

(defun report-framework-metadata (options stream)
  (let ((metadata (framework-metadata)))
    (case (metadata-reporter options)
      (:json (write-framework-metadata-json metadata stream))
      (:sexp (write metadata :stream stream :pretty t)
             (terpri stream)))))

(defun report-doctor (options stream)
  (let ((report (doctor-report options)))
    (case (doctor-reporter options)
      (:json (write-doctor-report-json report stream))
      (:sexp (write report :stream stream :pretty t)
             (terpri stream)))))
