(defpackage #:cl-weave
  (:use #:cl)
  (:shadow #:describe)
  (:export
   #:*test-context*
   #:around-each
   #:after-all
   #:afterall
   #:after-each
   #:aftereach
   #:assertion-failure
   #:before-all
   #:beforeall
   #:before-each
   #:beforeeach
   #:clear-tests
   #:collect-test-plan
   #:collect-mutations
   #:continue-test
   #:coverage-support-available-p
   #:coverage-unavailable
   #:coverage-unavailable-reason
   #:defmutation-operator
   #:describe
   #:describe.concurrent
   #:describe-concurrent
   #:describe.concurrent.each
   #:describe-concurrent-each
   #:describe.each
   #:describe-each
   #:describe.only
   #:describe-only
   #:describe.only.each
   #:describe-only-each
   #:describe.run-if
   #:describe-run-if
   #:describe.sequential
   #:describe-sequential
   #:describe.sequential.each
   #:describe-sequential-each
   #:describe.skip
   #:describe-skip
   #:describe.skip.each
   #:describe-skip-each
   #:describe.skip-if
   #:describe-skip-if
   #:describe.todo
   #:describe-todo
   #:defmatcher
   #:extend-expect
   #:expect
   #:expect.extend
   #:expect-extend
   #:expect.not
   #:expect-not
   #:expected-failure-missed
   #:expected-failure-missed-reason
   #:gen-boolean
   #:gen-integer
   #:gen-keyword
   #:gen-list
   #:gen-map
   #:gen-member
   #:gen-one-of
   #:gen-recursive
   #:gen-form
   #:gen-sexp
   #:gen-such-that
   #:gen-symbol
   #:gen-tuple
   #:*isolated-timeout-seconds*
   #:assert-isolated-success
   #:isolated-result
   #:isolated-result-elapsed-ms
   #:isolated-result-exit-code
   #:isolated-result-script-path
   #:isolated-result-status
   #:isolated-result-stderr
   #:isolated-result-stdout
   #:isolated-result-timed-out-p
   #:it
   #:it.concurrent
   #:it-concurrent
   #:it.concurrent.each
   #:it-concurrent-each
   #:it.each
   #:it-each
   #:it.fails
   #:it-fails
   #:it.fails.each
   #:it-fails-each
   #:it.isolated
   #:it-isolated
   #:it.property
   #:it-property
   #:it.only
   #:it-only
   #:it.only.each
   #:it-only-each
   #:it.run-if
   #:it-run-if
   #:it.sequential
   #:it-sequential
   #:it.sequential.each
   #:it-sequential-each
   #:it.skip
   #:it-skip
   #:it.skip.each
   #:it-skip-each
   #:it.skip-if
   #:it-skip-if
   #:it.todo
   #:it-todo
   #:list-tests
   #:logic-query
   #:logic-variable-p
   #:logic-where
   #:mutation
   #:mutation-form
   #:mutation-id
   #:mutation-operator
   #:mutation-original
   #:mutation-path
   #:mutation-replacement
   #:mutation-result
   #:mutation-result-condition
   #:mutation-result-mutation
   #:mutation-result-status
   #:mutation-summary
   #:*property-seed*
   #:*property-test-count*
   #:*snapshot-directory*
   #:*snapshot-file-name*
   #:*update-snapshots*
   #:with-snapshot-updates
   #:clear-mock
   #:make-mock-function
   #:mock-calls
   #:mock-results
   #:*test-sequence-order*
   #:*test-sequence-seed*
   #:*test-name-filter*
   #:asdf-system-files
   #:report-mutations-json
   #:report-mutations-sexp
   #:run-all
   #:run-isolated
   #:run-mutations
   #:run-system
   #:query-test-plan
   #:reset-coverage
   #:save-coverage
   #:retry-test
   #:skip-test
   #:test-plan-entry
   #:test-plan-entry-focused
   #:test-plan-entry-location
   #:test-plan-entry-path
   #:test-plan-entry-reason
   #:test-plan-entry-retry
   #:test-plan-entry-status
   #:test-plan-entry-timeout-ms
   #:test-plan-entry-concurrent
   #:test-plan-facts
   #:test-plan-where
   #:test
   #:test.concurrent
   #:test-concurrent
   #:test.concurrent.each
   #:test-concurrent-each
   #:test.each
   #:test-each
   #:test.fails
   #:test-fails
   #:test.fails.each
   #:test-fails-each
   #:test.isolated
   #:test-isolated
   #:test.only
   #:test-only
   #:test.only.each
   #:test-only-each
   #:test.property
   #:test-property
   #:test.run-if
   #:test-run-if
   #:test.sequential
   #:test-sequential
   #:test.sequential.each
   #:test-sequential-each
   #:test.skip
   #:test-skip
   #:test.skip.each
   #:test-skip-each
   #:test.skip-if
   #:test-skip-if
   #:test.todo
   #:test-todo
   #:test-failure
   #:test-timeout
   #:test-timeout-ms
   #:watch-system
   #:with-mocked-functions))

(defpackage #:cl-weave/cli
  (:use #:cl)
  (:export
   #:main))
