(defpackage #:cl-weave
  (:use #:cl)
  (:shadow #:describe)
  (:export
   #:*test-context*
   #:after-all
   #:after-each
   #:assertion-failure
   #:before-all
   #:before-each
   #:clear-tests
   #:describe
   #:describe-only
   #:expect
   #:gen-boolean
   #:gen-integer
   #:gen-list
   #:gen-member
   #:gen-one-of
   #:gen-such-that
   #:gen-tuple
   #:it
   #:it-each
   #:it-property
   #:it-only
   #:it-skip
   #:it-todo
   #:*property-seed*
   #:*property-test-count*
   #:*snapshot-directory*
   #:*update-snapshots*
   #:with-snapshot-updates
   #:clear-mock
   #:make-mock-function
   #:mock-calls
   #:*test-name-filter*
   #:run-all
   #:test
   #:test-only
   #:test-skip
   #:test-todo
   #:test-failure
   #:with-mocked-functions))
