(defpackage #:cl-weave/metadata
  (:use #:cl)
  (:export
   #:framework-metadata
   #:*metadata-commands*
   #:*metadata-cli-options*
   #:metadata-cli-options
   #:cli-option-usage-lines
   #:cli-version
   #:write-doctor-report-json))

(defpackage #:cl-weave
  (:use #:cl)
  (:shadow #:describe)
  (:import-from #:cl-weave/metadata
   #:framework-metadata)
  (:export
   #:framework-metadata
   #:*test-context*
   #:around-each
   #:after-all
   #:after-each
   #:assert-mutation-score
   #:assertion-failure
   #:before-all
   #:before-each
   #:clear-tests
   #:collect-test-plan
   #:collect-mutations
   #:continue-test
   #:coverage-support-available-p
   #:coverage-unavailable
   #:coverage-unavailable-reason
   #:defmutation-operator
   #:describe
   #:describe-concurrent
   #:describe-each
   #:describe-only
   #:describe-only-each
   #:describe-run-if
   #:describe-sequential
   #:describe-skip
   #:describe-skip-each
   #:describe-skip-if
   #:describe-todo
   #:describe-todo-each
   #:defmatcher
   #:extend-expect
   #:explain!
   #:expect
   #:expect-assertions
   #:expect-extend
   #:expect-has-assertions
   #:expect-not
   #:expect-poll
   #:expect-rejects
   #:expect-resolves
   #:expected-failure-missed
   #:expected-failure-missed-reason
   #:fail
   #:finishes
   #:gen-boolean
   #:gen-character
   #:gen-integer
   #:gen-keyword
   #:gen-list
   #:gen-map
   #:gen-member
   #:gen-one-of
   #:gen-recursive
   #:gen-form
   #:gen-sexp
   #:gen-state-machine
   #:gen-string
   #:gen-such-that
   #:gen-symbol
   #:gen-tuple
   #:gen-vector
   #:hook-failure
   #:hook-failure-causes
   #:hook-failure-phase
   #:*isolated-timeout-seconds*
   #:isolated-result
   #:isolated-result-elapsed-ms
   #:isolated-result-exit-code
   #:isolated-result-home-path
   #:isolated-result-script-path
   #:isolated-result-status
   #:isolated-result-stderr
   #:isolated-result-stderr-path
   #:isolated-result-stdout
   #:isolated-result-stdout-path
   #:isolated-result-timed-out-p
   #:it
   #:it-concurrent
   #:it-concurrent-each
   #:it-each
   #:it-fails
   #:it-fails-each
   #:it-isolated
   #:it-property
   #:it-only
   #:it-only-each
   #:it-run-if
   #:it-sequential
   #:it-sequential-each
   #:it-skip
   #:it-skip-each
   #:it-skip-if
   #:it-todo
   #:it-todo-each
   #:list-tests
   #:logic-program
   #:logic-query
   #:logic-search-exhausted
   #:logic-search-exhausted-limit
   #:logic-search-exhausted-partial-results
   #:logic-search-exhausted-pending
   #:logic-search-exhausted-steps
   #:increase-limit
   #:return-partial-results
   #:logic-run
   #:logic-variable-p
   #:logic-where
   #:list-matchers
   #:list-mutation-operators
   #:matcher
   #:matcher-description
   #:matcher-metadata
   #:matcher-name
   #:mutation
   #:mutation-form
   #:mutation-id
   #:mutation-operator
   #:mutation-operator-description
   #:mutation-operator-metadata
   #:mutation-operator-name
   #:mutation-original
   #:mutation-path
   #:mutation-replacement
   #:mutation-result
   #:mutation-result-condition
   #:mutation-result-mutation
   #:mutation-result-status
   #:mutation-score-failure
   #:mutation-score-failure-min-score
   #:mutation-score-failure-summary
   #:mutation-score-passes-p
   #:mutation-summary
   #:*property-seed*
   #:*property-shrink-max-steps*
   #:*property-test-count*
   #:property-shrink-limit
   #:property-shrink-limit-max-steps
   #:property-shrink-limit-steps
   #:property-shrink-limit-values
   #:accept-current
   #:property-shrinker-error
   #:property-shrinker-error-cause
   #:property-shrinker-error-generator
   #:property-shrinker-error-value
   #:retry-shrinker
   #:same-property-failure-p
   #:skip-shrinking
   #:*snapshot-directory*
   #:*snapshot-file-name*
   #:*update-snapshots*
   #:snapshot-entries
   #:snapshot-value
   #:with-snapshot-updates
   #:with-continuation-result
   #:with-continuation-values
   #:with-cleared-hash-table
   #:clear-all-mocks
   #:clear-mock
   #:make-mock-function
   #:mock-function-p
   #:mock-implementation
   #:mock-return-value
   #:mock-return-values
   #:reset-all-mocks
   #:reset-mock
   #:restore-all-mocks
   #:reporter-artifact-schemas
   #:run-reporters
   #:list-reporters
   #:skip
   #:mock-restore
   #:spy-on
   #:mock-calls
   #:mock-results
   #:*test-sequence-order*
   #:*test-sequence-seed*
   #:*test-name-filter*
   #:*default-retry*
   #:*default-timeout-ms*
   #:asdf-system-files
   #:report-mutations-json
   #:report-mutations-sexp
   #:results-status
   #:run
   #:run-all
   #:run-isolated
   #:run-mutations
   #:run-system
   #:signals
   #:query-test-plan
   #:reset-coverage
   #:save-coverage
   #:retry-test
   #:skip-test
   #:test-plan-entry
   #:test-plan-entry-focused
   #:test-plan-entry-location
   #:test-plan-entry-path
   #:test-plan-entry-reason
   #:test-plan-entry-retry
   #:test-plan-entry-status
   #:test-plan-entry-timeout-ms
   #:test-plan-entry-concurrent
   #:test-plan-facts
   #:test-plan-where
   #:test-failure
   #:test-timeout
   #:test-timeout-ms
   #:*max-workers*
   #:watch-system
   #:with-mocked-functions
   #:with-replaced-function
   #:with-restored-binding
   #:with-restored-bindings
   #:with-restored-hash-table))

(defpackage #:cl-weave/cli
  (:use #:cl)
  (:import-from #:cl-weave/metadata
   #:*metadata-commands*
   #:*metadata-cli-options*
   #:metadata-cli-options
   #:cli-option-usage-lines
   #:cli-version
   #:write-doctor-report-json)
  (:export
   #:main))
