(in-package #:cl-weave)

(defun plan-status-marker (status)
  (ecase status
    (:run "RUN")
    (:skip "SKIP")
    (:todo "TODO")))

(defun serializable-plan-entry (entry)
  (list :status (test-plan-entry-status entry)
        :path (test-plan-entry-path entry)
        :path-string (path-string (test-plan-entry-path entry))
        :location (test-plan-entry-location entry)
        :reason (test-plan-entry-reason entry)
        :focused (test-plan-entry-focused entry)
        :retry (test-plan-entry-retry entry)
        :timeout-ms (test-plan-entry-timeout-ms entry)
        :concurrent (test-plan-entry-concurrent entry)
        :tags (test-plan-entry-tags entry)
        :depends-on (test-plan-entry-depends-on entry)))

(defun report-plan-spec (plan stream)
  (let ((summary (plan-summary plan)))
  (dolist (entry plan)
    (format stream "~&[~A] ~A"
            (plan-status-marker (test-plan-entry-status entry))
            (path-string (test-plan-entry-path entry)))
    (when (test-plan-entry-focused entry)
      (write-string " (focused)" stream))
    (when (test-plan-entry-reason entry)
      (format stream "~&    reason: ~A" (test-plan-entry-reason entry))))
  (format stream "~&~%~D runnable, ~D skipped, ~D todo, ~D total~%"
          (getf summary :runnable)
          (getf summary :skipped)
          (getf summary :todos)
          (getf summary :total))
  (values)))

(defun report-plan-sexp (plan stream)
  (let ((summary (plan-summary plan)))
    (prin1 (append (list :cl-weave/test-plan
                         :schema-version 3)
                   summary
                   (list :tests (mapcar #'serializable-plan-entry plan)))
           stream))
  (terpri stream)
  (values))

(defun json-write-plan-metadata-list (values stream)
  (json-write-array values stream))

(defun json-write-plan-entry (entry stream)
  (write-string "{" stream)
  (write-string "\"status\":" stream)
  (write-json-string (json-status-string (test-plan-entry-status entry)) stream)
  (write-string ",\"path\":" stream)
  (json-write-path (test-plan-entry-path entry) stream)
  (write-string ",\"pathString\":" stream)
  (write-json-string (path-string (test-plan-entry-path entry)) stream)
  (write-string ",\"location\":" stream)
  (json-write-location (test-plan-entry-location entry) stream)
  (write-string ",\"reason\":" stream)
  (json-write-nullable-string (test-plan-entry-reason entry) stream)
  (write-string ",\"focused\":" stream)
  (write-string (if (test-plan-entry-focused entry) "true" "false") stream)
  (format stream ",\"retry\":~D" (test-plan-entry-retry entry))
  (write-string ",\"timeoutMs\":" stream)
  (let ((timeout-ms (test-plan-entry-timeout-ms entry)))
    (if timeout-ms
        (princ timeout-ms stream)
        (write-string "null" stream)))
  (write-string ",\"concurrent\":" stream)
  (write-string (if (test-plan-entry-concurrent entry) "true" "false") stream)
  (write-string ",\"tags\":" stream)
  (json-write-plan-metadata-list (test-plan-entry-tags entry) stream)
  (write-string ",\"dependsOn\":" stream)
  (json-write-plan-metadata-list (test-plan-entry-depends-on entry) stream)
  (write-string "}" stream))

(defun report-plan-json (plan stream)
  (let ((summary (plan-summary plan)))
  (write-string "{" stream)
  (write-string "\"schemaVersion\":3" stream)
  (write-string ",\"kind\":\"test-plan\"" stream)
  (format stream ",\"total\":~D" (getf summary :total))
  (json-write-summary-count-fields summary *plan-summary-field-specs* stream)
  (write-string ",\"tests\":" stream)
  (json-write-sequence plan #'json-write-plan-entry stream)
  (write-string "}" stream)
  (terpri stream)
  (values)))

(defun report-plan-jsonl (plan stream)
  (let ((summary (plan-summary plan)))
  (write-string "{\"schemaVersion\":1,\"kind\":\"test-plan-start\",\"total\":" stream)
  (princ (getf summary :total) stream)
  (write-string "}" stream)
  (terpri stream)
  (dolist (entry plan)
    (write-string "{\"schemaVersion\":2,\"kind\":\"test-plan-entry\",\"test\":" stream)
    (json-write-plan-entry entry stream)
    (write-string "}" stream)
    (terpri stream))
  (write-string "{\"schemaVersion\":1,\"kind\":\"test-plan-summary\"" stream)
  (format stream ",\"total\":~D" (getf summary :total))
  (json-write-summary-count-fields summary *plan-summary-field-specs* stream)
  (write-string "}" stream)
  (terpri stream)
  (values)))

