(in-package #:cl-weave)

(defun serializable-mutation (mutation)
  (list :id (mutation-id mutation)
        :operator (mutation-operator mutation)
        :path (mutation-path mutation)
        :original (mutation-original mutation)
        :replacement (mutation-replacement mutation)
        :form (mutation-form mutation)))

(defun serializable-mutation-result (result)
  (list :status (mutation-result-status result)
        :condition (when (mutation-result-condition result)
                     (princ-to-string (mutation-result-condition result)))
        :mutation (serializable-mutation (mutation-result-mutation result))))

(defun report-mutations-sexp (results stream)
  (prin1 (list :cl-weave/mutations
               :schema-version 1
               :summary (mutation-summary results)
               :results (mapcar #'serializable-mutation-result results))
         stream)
  (terpri stream)
  (values))

(defun json-write-integer-list (values stream)
  (json-write-sequence values #'princ stream))

(defun json-write-mutation (mutation stream)
  (write-string "{" stream)
  (format stream "\"id\":~D" (mutation-id mutation))
  (write-string ",\"operator\":" stream)
  (write-json-string (mutation-operator mutation) stream)
  (write-string ",\"path\":" stream)
  (json-write-integer-list (mutation-path mutation) stream)
  (write-string ",\"original\":" stream)
  (json-write-printed-value (mutation-original mutation) stream)
  (write-string ",\"replacement\":" stream)
  (json-write-printed-value (mutation-replacement mutation) stream)
  (write-string ",\"form\":" stream)
  (json-write-printed-value (mutation-form mutation) stream)
  (write-string "}" stream))

(defun json-write-mutation-result (result stream)
  (write-string "{" stream)
  (write-string "\"status\":" stream)
  (write-json-string (json-status-string (mutation-result-status result)) stream)
  (write-string ",\"condition\":" stream)
  (json-write-nullable-string
   (when (mutation-result-condition result)
     (princ-to-string (mutation-result-condition result)))
   stream)
  (write-string ",\"mutation\":" stream)
  (json-write-mutation (mutation-result-mutation result) stream)
  (write-string "}" stream))

(defun report-mutations-json (results stream)
  (let ((summary (mutation-summary results)))
    (write-string "{" stream)
    (write-string "\"schemaVersion\":1" stream)
    (write-string ",\"kind\":\"mutations\"" stream)
    (format stream ",\"total\":~D" (getf summary :total))
    (format stream ",\"killed\":~D" (getf summary :killed))
    (format stream ",\"survived\":~D" (getf summary :survived))
    (format stream ",\"errored\":~D" (getf summary :errored))
    (format stream ",\"score\":~,6F" (getf summary :score))
    (write-string ",\"results\":" stream)
    (json-write-sequence results #'json-write-mutation-result stream)
    (write-string "}" stream)
    (terpri stream)
    (values)))

