name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  nix:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v17
      - run: nix flake check
